# Generated by Django 2.0.5 on 2018-05-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('additions', models.IntegerField(blank=True, null=True)),
                ('message', models.CharField(max_length=1020)),
            ],
        ),
    ]
