# Generated by Django 2.0.4 on 2018-05-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='rsvp',
            field=models.BooleanField(default=False),
        ),
    ]
