# Generated by Django 2.0.4 on 2018-05-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0003_guest_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
